// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPwLpbK1z1rkyYLycRqFpDMcJSfErJdqg',
    appId: '1:944577942192:web:f842e9e9e11462d8dca175',
    messagingSenderId: '944577942192',
    projectId: 'rawisbmetro-47fa3',
    authDomain: 'rawisbmetro-47fa3.firebaseapp.com',
    storageBucket: 'rawisbmetro-47fa3.firebasestorage.app',
    measurementId: 'G-71MX4GJBCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBLrjqDlujqrWNIIyIH4OSTWPHZv4XNc',
    appId: '1:944577942192:android:cbc1ecb2322bcfa5dca175',
    messagingSenderId: '944577942192',
    projectId: 'rawisbmetro-47fa3',
    storageBucket: 'rawisbmetro-47fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDx0U2oU3FkDWzsxmDi91kHR-cvlS4M8E',
    appId: '1:944577942192:ios:228ba6b3b0a98c8edca175',
    messagingSenderId: '944577942192',
    projectId: 'rawisbmetro-47fa3',
    storageBucket: 'rawisbmetro-47fa3.firebasestorage.app',
    iosBundleId: 'com.example.rawalpindiIsbMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDx0U2oU3FkDWzsxmDi91kHR-cvlS4M8E',
    appId: '1:944577942192:ios:228ba6b3b0a98c8edca175',
    messagingSenderId: '944577942192',
    projectId: 'rawisbmetro-47fa3',
    storageBucket: 'rawisbmetro-47fa3.firebasestorage.app',
    iosBundleId: 'com.example.rawalpindiIsbMetro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPwLpbK1z1rkyYLycRqFpDMcJSfErJdqg',
    appId: '1:944577942192:web:43b37f58224a5293dca175',
    messagingSenderId: '944577942192',
    projectId: 'rawisbmetro-47fa3',
    authDomain: 'rawisbmetro-47fa3.firebaseapp.com',
    storageBucket: 'rawisbmetro-47fa3.firebasestorage.app',
    measurementId: 'G-M9YJ3GMYV3',
  );

}